services:
  - type: web
    name: client-side
    env: node
    plan: free
    build:
      cwd: .
      buildCommand: npm ci && npm run build
      staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22.16.0


